[2024-12-02T14:25:39.605+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T14:25:39.689+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:25:32.995442+00:00 [queued]>
[2024-12-02T14:25:39.707+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:25:32.995442+00:00 [queued]>
[2024-12-02T14:25:39.708+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T14:25:39.724+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 09:25:32.995442+00:00
[2024-12-02T14:25:39.733+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=52473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T14:25:39.735+0500] {standard_task_runner.py:72} INFO - Started process 52483 to run task
[2024-12-02T14:25:39.737+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T09:25:32.995442+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmp56ph2kdh']
[2024-12-02T14:25:39.743+0500] {standard_task_runner.py:105} INFO - Job 24: Subtask extract_from_api
[2024-12-02T14:25:39.830+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:25:32.995442+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T14:25:39.953+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T09:25:32.995442+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T09:25:32.995442+00:00'
[2024-12-02T14:25:39.955+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T14:25:39.982+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?
[2024-12-02T14:25:39.983+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?lat=31.5204&lon=74.3587&appid=7ffe28e7eea4bb7870bd861ff09cfb80
[2024-12-02T14:25:39.985+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T14:26:15.073+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-02T14:26:15.075+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T14:26:15.089+0500] {process_utils.py:132} INFO - Sending 15 to group 52483. PIDs of all processes in the group: [52483]
[2024-12-02T14:26:15.089+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 52483
[2024-12-02T14:27:15.095+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=52483, name='python3.12', status='running', started='14:25:39') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T14:27:15.096+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 52483
[2024-12-02T14:27:15.104+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=52483, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='14:25:39') (52483) terminated with exit code -9
[2024-12-02T14:27:15.105+0500] {standard_task_runner.py:190} ERROR - ('Job 24 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
