[2024-12-02T13:28:31.110+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T13:28:31.122+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:28:26.714560+00:00 [queued]>
[2024-12-02T13:28:31.130+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:28:26.714560+00:00 [queued]>
[2024-12-02T13:28:31.130+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T13:28:31.143+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 08:28:26.714560+00:00
[2024-12-02T13:28:31.149+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=48933) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T13:28:31.151+0500] {standard_task_runner.py:72} INFO - Started process 48937 to run task
[2024-12-02T13:28:31.152+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T08:28:26.714560+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmpticxx571']
[2024-12-02T13:28:31.156+0500] {standard_task_runner.py:105} INFO - Job 12: Subtask extract_from_api
[2024-12-02T13:28:31.205+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:28:26.714560+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T13:28:31.279+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:28:26.714560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:28:26.714560+00:00'
[2024-12-02T13:28:31.280+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T13:28:31.308+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T13:29:46.776+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-02T13:29:46.778+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T13:29:46.792+0500] {process_utils.py:132} INFO - Sending 15 to group 48937. PIDs of all processes in the group: [48937]
[2024-12-02T13:29:46.792+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 48937
[2024-12-02T13:30:46.795+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=48937, name='python3.12', status='running', started='13:28:31') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T13:30:46.796+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 48937
[2024-12-02T13:30:46.812+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=48937, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:28:31') (48937) terminated with exit code -9
[2024-12-02T13:30:46.813+0500] {standard_task_runner.py:190} ERROR - ('Job 12 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
