[2024-12-02T13:52:53.088+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T13:52:53.100+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:52:49.056038+00:00 [queued]>
[2024-12-02T13:52:53.107+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:52:49.056038+00:00 [queued]>
[2024-12-02T13:52:53.107+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T13:52:53.119+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 08:52:49.056038+00:00
[2024-12-02T13:52:53.125+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50525) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T13:52:53.127+0500] {standard_task_runner.py:72} INFO - Started process 50529 to run task
[2024-12-02T13:52:53.128+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T08:52:49.056038+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmpbja6kbp7']
[2024-12-02T13:52:53.133+0500] {standard_task_runner.py:105} INFO - Job 17: Subtask extract_from_api
[2024-12-02T13:52:53.177+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:52:49.056038+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T13:52:53.248+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:52:49.056038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:52:49.056038+00:00'
[2024-12-02T13:52:53.249+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T13:52:53.268+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?
[2024-12-02T13:52:53.269+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T13:54:54.138+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-02T13:54:54.145+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T13:54:54.262+0500] {process_utils.py:132} INFO - Sending 15 to group 50529. PIDs of all processes in the group: [50529]
[2024-12-02T13:54:54.262+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 50529
[2024-12-02T13:55:54.283+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=50529, name='python3.12', status='running', started='13:52:53') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T13:55:54.286+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 50529
[2024-12-02T13:55:54.295+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=50529, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:52:53') (50529) terminated with exit code -9
[2024-12-02T13:55:54.296+0500] {standard_task_runner.py:190} ERROR - ('Job 17 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
