[2024-12-02T13:31:14.928+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T13:31:14.941+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:31:10.888466+00:00 [queued]>
[2024-12-02T13:31:14.950+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:31:10.888466+00:00 [queued]>
[2024-12-02T13:31:14.950+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T13:31:14.968+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 08:31:10.888466+00:00
[2024-12-02T13:31:14.977+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=49070) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T13:31:14.978+0500] {standard_task_runner.py:72} INFO - Started process 49074 to run task
[2024-12-02T13:31:14.980+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T08:31:10.888466+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmps8ku0vm_']
[2024-12-02T13:31:14.989+0500] {standard_task_runner.py:105} INFO - Job 13: Subtask extract_from_api
[2024-12-02T13:31:15.049+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:31:10.888466+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T13:31:15.133+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:31:10.888466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:31:10.888466+00:00'
[2024-12-02T13:31:15.135+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T13:31:15.166+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T13:36:57.441+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-02T13:36:57.443+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T13:36:57.457+0500] {process_utils.py:132} INFO - Sending 15 to group 49074. PIDs of all processes in the group: [49074]
[2024-12-02T13:36:57.458+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 49074
[2024-12-02T13:37:57.544+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=49074, name='python3.12', status='running', started='13:31:14') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T13:37:57.546+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 49074
[2024-12-02T13:37:57.555+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=49074, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:31:14') (49074) terminated with exit code -9
[2024-12-02T13:37:57.557+0500] {standard_task_runner.py:190} ERROR - ('Job 13 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
